============================= test session starts ==============================
platform linux -- Python 3.8.2, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/devasc/Documents/activities/Activity-02-23-2022
plugins: Faker-4.1.1
collected 4 items

test_multiply.py F                                                       [ 25%]
test_run.py F                                                            [ 50%]
test_square.py .F                                                        [100%]

=================================== FAILURES ===================================
_________________________________ MyTest.test __________________________________

self = <test_multiply.MyTest testMethod=test>

    def test(self):
>       self.assertEqual(multiply(3, 2), 8)
E       AssertionError: 6 != 8

test_multiply.py:10: AssertionError
_________________________________ MyTest.test __________________________________

self = <test_run.MyTest testMethod=test>

    def test(self):
>       self.assertEqual(fun(4), 6)
E       AssertionError: 5 != 6

test_run.py:10: AssertionError
_________________________________ test_square __________________________________

    def test_square():
        num = 7
>       assert num * num == 40
E       assert (7 * 7) == 40

test_square.py:11: AssertionError
=========================== short test summary info ============================
FAILED test_multiply.py::MyTest::test - AssertionError: 6 != 8
FAILED test_run.py::MyTest::test - AssertionError: 5 != 6
FAILED test_square.py::test_square - assert (7 * 7) == 40
========================= 3 failed, 1 passed in 0.27s ==========================
